### ISSUE TITLE
Connection to Metamask

### ISSUE THREAD

**Issue by varunpareek690** [SassiBen/Blockchain-Based-Wedding-Certificate-System#1]
# Hi I am learning Blockchain through your project
# I am unable to connect to metamask 
# Also how do I get the ABI and json file of contracts and how to deploy them

**Comment by SassiBen** [comment]
# Project Guide

Hello,

Thank you for your interest in the project. I'm glad you're using it to learn more about blockchain. Let's address your questions step by step:

## A- Connecting to MetaMask:

1. Ensure you have the MetaMask extension installed in your browser. If not, you can download it.
2. Once installed, open MetaMask and create an account or log in to your existing account.
3. To connect the project to MetaMask, please make sure you're running the project on a local server (if applicable, I use HTTP local server) and that your browser's MetaMask extension is active and logged in.
4. The connection might also depend on the network settings within your MetaMask. Ensure that your MetaMask is set to the correct network that the smart contract is deployed on (e.g., Ethereum Mainnet, Sepolia Testnet, etc.).

## B- Getting the ABI and JSON File:

1. ABI is crucial for interacting with smart contracts. The ABI and the contract's JSON file are usually generated when you compile the smart contract using a development environment like Truffle or Remix (I use Remix).
2. If using Truffle, the `truffle compile` command compiles your contracts, and the ABI is part of the output JSON files located in the `build/contracts` directory.
3. For Remix, After successful compilation, in the "Solidity Compiler" tab, scroll down to the "Compilation Details" section. Find the contract you're interested in and click on the button labeled "ABI" next to it. This will copy the ABI to your clipboard. You can paste this ABI into a JSON file manually or into the application's code where it's needed to interact with the smart contract.

## C- Deploying the Contracts:
To deploy the contracts, you need a development environment like Truffle, Remix or Hardhat.
### Using Remix:
1. To deploy using MetaMask, In Remix, go to the "Deploy & Run Transactions" panel on the left sidebar.
2. At the environment dropdown, select "Injected Web3". Remix will automatically attempt to connect to MetaMask.
3. MetaMask should prompt you to connect to Remix. Confirm the connection. If it's your first time connecting, you may need to select the account you wish to use for deploying.
#### Selecting the Network:
Ensure MetaMask is set to the correct network where you want to deploy your contract (e.g., Sepolia Testnet). You can switch networks in MetaMask by clicking on the network name at the top of the MetaMask window and selecting the network you wish to use.
#### Deploying the Contract:
1. In the "Deploy & Run Transactions" panel in Remix, make sure the correct contract is selected in the "Contract" dropdown. Fill in any constructor parameters your contract may require directly in the Remix interface.
2. Click the "Deploy" button. MetaMask will prompt you to confirm the transaction, showing the gas fee and allowing you to adjust it if necessary.
3. Confirm the transaction in MetaMask. The deployment will start, and it may take a few moments to complete, depending on the network congestion and the gas fee you've set.
4. Once the transaction is confirmed, your contract is deployed, Remix will show the deployed contract under the "Deployed Contracts" section in the "Deploy & Run Transactions" panel. Here, you can interact with your contract's functions.
### Accessing Deployed Contract Information:

After deployment, you can click on the deployed contract in Remix to access its address, ABI, and functions. The contract address is crucial for interacting with your contract on the blockchain. Ensure to note it down. For the ABI, you can use the method described previously to copy it from the "Solidity Compiler" tab.

I hope this helps clear up the process.

Best regards,

Sassi

**Comment by varunpareek690** [comment]
* Hey! Thank you very much! I will try once again!
